-- AlterTable
ALTER TABLE `audit_logs` MODIFY `action` ENUM('PRICE_UPDATE', 'STOCK_DELETE', 'LOGIN', 'LOGOUT', 'REGISTER', 'EMPLOYEE_CREATE', 'EMPLOYEE_UPDATE', 'EMPLOYEE_DELETE', 'SALE_CREATE', 'SALE_UPDATE', 'SALE_DELETE', 'PURCHASE_CREATE', 'PURCHASE_UPDATE', 'PURCHASE_DELETE', 'PRODUCT_CREATE', 'PRODUCT_UPDATE', 'PRODUCT_DELETE', 'EXPENSE_CREATE', 'RETURN_CREATE', 'TRADE_CREATE') NOT NULL;
