/*
  Warnings:

  - The values [STOCK_DELETE,CUSTOMER_CREATE,CUSTOMER_UPDATE,CUSTOMER_DELETE,PURCHASE_UPDATE,PURCHASE_DELETE,PRODUCT_CREATE,PRODUCT_UPDATE,PRODUCT_DELETE,EXPENSE_UPDATE,EXPENSE_DELETE,RETURN_CREATE,TRADE_CREATE] on the enum `audit_logs_action` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterTable
ALTER TABLE `audit_logs` MODIFY `action` ENUM('LOGIN', 'LOGOUT', 'REGISTER', 'EMPLOYEE_CREATE', 'EMPLOYEE_UPDATE', 'EMPLOYEE_DELETE', 'SALE_CREATE', 'SALE_UPDATE', 'SALE_DELETE', 'PURCHASE_CREATE', 'EXPENSE_CREATE', 'PRICE_UPDATE', 'STOCK_ADJUSTMENT') NOT NULL;
