-- AlterTable
ALTER TABLE `audit_logs` MODIFY `action` ENUM('LOGIN', 'LOGOUT', 'REGISTER', 'EMPLOYEE_CREATE', 'EMPLOYEE_UPDATE', 'EMPLOYEE_DELETE', 'SALE_CREATE', 'SALE_UPDATE', 'SALE_DELETE', 'PURCHASE_CREATE', 'EXPENSE_CREATE', 'EXPENSE_DELETE', 'INCOME_CREATE', 'INCOME_DELETE', 'PRICE_UPDATE', 'STOCK_ADJUSTMENT') NOT NULL;
