-- AlterTable
ALTER TABLE `purchases` MODIFY `status` ENUM('COMPLETED', 'RETURNED', 'PARTIALLY_RETURNED', 'CANCELLED') NOT NULL DEFAULT 'COMPLETED';

-- AlterTable
ALTER TABLE `returns` ADD COLUMN `status` ENUM('COMPLETED', 'RETURNED', 'PARTIALLY_RETURNED', 'CANCELLED') NOT NULL DEFAULT 'COMPLETED';

-- AlterTable
ALTER TABLE `sales` MODIFY `status` ENUM('COMPLETED', 'RETURNED', 'PARTIALLY_RETURNED', 'CANCELLED') NOT NULL DEFAULT 'COMPLETED';

-- AlterTable
ALTER TABLE `supplier_returns` ADD COLUMN `status` ENUM('COMPLETED', 'RETURNED', 'PARTIALLY_RETURNED', 'CANCELLED') NOT NULL DEFAULT 'COMPLETED';

-- AlterTable
ALTER TABLE `trades` ADD COLUMN `status` ENUM('COMPLETED', 'RETURNED', 'PARTIALLY_RETURNED', 'CANCELLED') NOT NULL DEFAULT 'COMPLETED';
